### ISSUE TITLE
KeyError: 'BypassAntibot'

### ISSUE THREAD

**Issue by vaako8919** [j4rj4r/Selenium-Twitter#4]
Erreur au Lancement du bot
![Capture d’écran 2022-07-08 142644](https://user-images.githubusercontent.com/70246467/177992655-c44291c5-c1f8-4a9e-bf5b-03fabb5b06a3.png)

**Comment by j4rj4r** [comment]
Fix ici : https://github.com/j4rj4r/Selenium-Twitter/commit/f90bc61740411c513d6ade52ecdff3ee8006bb96
